default:
  tags: [ 'smp-runner-shell' ]

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: $CI_REGISTRY/simplonprod/devops/docker-images/php/7.4
  script:
    - composer2 config -g cache-dir "$(pwd)/.composer-cache"
    - composer2 install
  artifacts:
    paths:
      - vendor
  allow_failure: false
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-php"
    policy: pull-push
    paths:
      - vendor
      - .composer-cache
  only:
    - master

test:
  stage: build
  image: $CI_REGISTRY/simplonprod/devops/docker-images/php/7.4-xdebug
  services:
    - mysql:5.6
  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: "db"
    MYSQL_USER: "db"
    MYSQL_PASSWORD: "db"
    MYSQL_ROOT_PASSWORD: "db"
  before_script:
    - cp tests/example-env tests/.env
  script:
    - ./vendor/bin/codecept run unit --no-colors --steps --xml --html --coverage --coverage-xml --coverage-html
  artifacts:
    paths:
      - tests/_output/report.xml
      - tests/_output/report.html
      - tests/_output/coverage.xml
      - tests/_output/coverage
    reports:
      junit: tests/_output/report.xml
  only:
    - master

deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag="$CI_COMMIT_TAG" "https://gitlab.ecedi.fr/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags
